import pandas as pd
import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Configrure Streamlit page
st.set_page_config(page_title="Sales Data Analysis", layout="wide")
#Title 
st.title("Sales Performance Analysis")

#Load data 
@st.cache_data
def load_data():
    df = pd.read_csv("sales_data.csv")
    df["Date"] = pd.to_datetime(df["Date"])
    return df       

df= load_data()



# Add sidebar filters
st.sidebar.header("Filters")

# Product filter
products = st.sidebar.multiselect(
    "Select Products",
    options=df['Product'].unique(),
    default=df['Product'].unique()
)

# Region filter
regions = st.sidebar.multiselect(
    "Select Regions",
    options=df['Region'].unique(),
    default=df['Region'].unique()
)

# Apply filters
df = df[df['Product'].isin(products) & df['Region'].isin(regions)]

# --- ADD THIS AT THE TOP (Below df = load_data()) ---

st.header("Product Sales Summary")

# Calculate total sales and count for each product
product_summary = df.groupby("Product")["Total"].agg(['sum', 'count']).rename(
    columns={'sum': 'Total Revenue ($)', 'count': 'Quantity Sold'}
).sort_values(by='Total Revenue ($)', ascending=False)

# Display the table with formatting
st.dataframe(
    product_summary.style.format({'Total Revenue ($)': '${:,.2f}', 'Quantity Sold': '{:,}'}),
    use_container_width=True
)

st.divider()
# --- THE KPI SECTION FOLLOWS BELOW THIS ---

#KPIS 
st.header("Key Metrics to measure Performances")

col1, col2, col3 = st.columns(3)

with col1:
    total_revenue = df["Total"].sum()
    st.metric("Total Revenue", f"${total_revenue:,.2f}")

with col2:
    total_sales= len(df)
    st.metric("Total Sales", f"${total_sales}")

with col3:
    avg_sales= df["Total"].mean()
    st.metric("Avg Sales", f"${avg_sales:,.2f}")

    st.divider()

    # Visulization 1: Sales by product bar graph
st.header("Total Sales by Product in USD")

prouct_revenue = df.groupby("Product")["Total"].sum().sort_values(ascending=False)


fig1, ax1 = plt.subplots(figsize=(10,6))


sns.barplot(

    x=prouct_revenue.values, 

    y=prouct_revenue.index, 

    ax=ax1,

    palette="viridis"  # Adds nice colors to your bars)

)

ax1.set_xlabel("Total Revenue ($)")

ax1.set_ylabel("Product Name")

ax1.set_title("Revenue Ranking by Product")

st.pyplot(fig1)

st.write("The bar graph above illustrates the total sales revenue generated by each product. It helps identify the top-performing products and those that may need more marketing focus.")
st.write("From the graph, we can see which products are driving the most revenue which happens to be Laptops followed by phones and tablets . This insight can guide inventory and promotional strategies for future.")

st.divider()

# Visualization 2: Sales over time line graph
st.header("Sales trend Over 12 months period")

df["Month"] = df["Date"].dt.to_period("M").astype(str)  # Converts raw data into monthly date string
monthly_sales = df.groupby("Month")["Total"].sum()
fig2, ax2 = plt.subplots(figsize=(12,8))
monthly_sales.plot(kind='line', marker='o', ax=ax2, color='red')
ax2.set_xlabel("Month")
ax2.set_ylabel("Total Sales in USD")
ax2.set_title("Monthly Sales Trend")
ax2.grid(True,alpha=0.3)  # This shows grid in the chart
ax2.set_xticks(range(len(monthly_sales)))
ax2.set_xticklabels(monthly_sales.index)
plt.xticks(rotation=45)  
st.pyplot(fig2)
st.subheader("Analysis & Insights")

st.markdown("""
* **Overview of the Chart:** The graph illustrates total sales over a 12-month period, helping identify seasonal patterns and overall growth or decline.
* **Seasonality & Peaks:** Sales peaked significantly around **February** and **November**, likely driven by holiday shopping like Thanks-Giving, Valentines Day and end-of-year promotions. Note:  This is just an assumption we can create hypothesis from it rather than jumping into conclusion.
* **Performance Dips:** A noticeable rise and dip occurs during the **mid-year months** the demand is constantly up and down while sales totally plumeted during  **December**, suggesting a potential off-season period .
* **Actionable Data:** These fluctuations are key for planning marketing campaigns and managing inventory to ensure stock is available during high-demand periods.
* **Note:** Further analysis could explore external factors influencing these trends, such as economic conditions or competitor actions we can just draw hypothesis from above data rather than jumping into conclusion.
""")

st.divider()

# Visualization 3: Sales by Region pie chart
st.header("Sales Distribution by Region")

fig3, ax3 = plt.subplots(figsize=(5,3))

region_sales=df.groupby("Region")["Total"].sum()
colors=sns.color_palette("pastel")
ax3.pie(
    region_sales.values,
    labels=region_sales.index,
    autopct='%1.1f%%',
    colors=colors,
    startangle=90
)
ax3.set_title("Sales Distribution by Region")
st.pyplot(fig3)

st.markdown("""
* **Overview of the Chart:** Shows the share of total sales for each region.
* **Key Insight:** The **West** region leads in sales, while other regions have similar contributions, indicating a balanced business presence across all regions.
""")

st.divider()


# Visualization 4: Regional Deep-Dive Comparison
st.header("Breakdown of Product Performance by Specific Region")

# Create 4 columns for a side-by-side view
reg_col1, reg_col2 = st.columns(2)
reg_col3, reg_col4 = st.columns(2)

regions_list = ['North', 'South', 'East', 'West']
cols = [reg_col1, reg_col2, reg_col3, reg_col4]
palettes = ["magma", "plasma", "viridis", "rocket"]

for i, region in enumerate(regions_list):
    with cols[i]:
        st.subheader(f"{region} Region")
        
        # Filter data for the specific region
        region_data = df[df['Region'] == region]
        
        if not region_data.empty:
            # Group and plot
            reg_prod_sales = region_data.groupby("Product")["Total"].sum().sort_values(ascending=False)
            
            fig, ax = plt.subplots(figsize=(8, 5))
            sns.barplot(
                x=reg_prod_sales.values, 
                y=reg_prod_sales.index, 
                ax=ax, 
                palette=palettes[i]
            )
            ax.set_xlabel("Revenue ($)")
            ax.set_ylabel("")
            st.pyplot(fig)
        else:
            st.info(f"No data selected for {region}")

            # Adding your specific insights in bullet points
st.subheader("Regional Performance Analysis")
st.markdown(f"""
* **The "Top Two" Dominance:** Phones and Laptops are the consistent top sellers across all regions. 
* **Regional Preferences:** In the **North and East**, Phones are the #1 revenue generator. In the **South and West**, Laptops take the lead.
* **Mid-Tier Revenue:** Tablets and Monitors contribute a noticeable share of revenue, representing the mid-range price point.
* **Volume vs. Value:** Chargers and Mouse bring in the least revenue. This is likely because they are low-priced accessory products compared to high-value electronics.
""")

st.divider()


st.divider()
